version: 2.1

workflows:
  test-workflow:
    jobs:
      - test-job

jobs:
  test-job:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run:
          name: Running test something
          command: |
            echo "hello world"


