version: 2.1

workflows:
  test-workflow:
    jobs:
      - test-job

jobs:
  test-job:
    docker:
      - image: buildpack-deps:trusty
      - image: circleci/mongo@sha256:9f445565981189224ed6cbe122f8085b51d9b0d69b3d3b3010dfab4236848721
        environment:
          - MONGO_INITDB_ROOT_USERNAME=root-test
          - MONGO_INITDB_ROOT_PASSWORD=pass-test
          - MONGODB_USER=root-test
          - MONGODB_PASS=pass-test
    steps:
      - run:
          name: Running test something
          command: |
            echo "hello world"


