version: 2
jobs:
  mongotest:
    docker:
      - image: mongo/3.6.13-xenial
      - image: circleci/mongo@sha256:9f445565981189224ed6cbe122f8085b51d9b0d69b3d3b3010dfab4236848721
        environment:
          - MONGO_INITDB_ROOT_USERNAME=root-test
          - MONGO_INITDB_ROOT_PASSWORD=pass-test
          - MONGODB_USER=root-test
          - MONGODB_PASS=pass-test
    steps:
      - run:
          name: sleep
          command: |
            sleep 3700
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - mongotest
