version: 2.1

workflows:
  test-workflow:
    jobs:
     - test-job

jobs:
  test-job:
    docker: true
    steps:
      - run:
         name: Running test something
         command: |
           echo "hello world"           


